# Generated by Django 5.0.6 on 2024-06-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='movies/')),
                ('description', models.TextField()),
                ('director', models.CharField(default='Unknown', max_length=255)),
                ('genre', models.CharField(default='Unknown', max_length=100)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
